# Generated by Django 3.1.5 on 2022-11-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adauga_cabinet',
            name='imagine',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='adauga_cabinet',
            name='imagine2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='adauga_cabinet',
            name='imagine3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='adauga_cabinet',
            name='imagine4',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='adauga_cabinet',
            name='imagine5',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='adauga_cabinet',
            name='imagine6',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='doctor',
            name='imagine',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pacient',
            name='imagine',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
