# Generated by Django 3.1.5 on 2022-11-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20221125_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='adauga_cabinet',
            name='departamente',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
