# Generated by Django 3.1.5 on 2022-11-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_adauga_cabinet_departamente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adauga_cabinet',
            name='departamente',
            field=models.CharField(choices=[('Chirurgie', 'Chirurgie'), ('Cardiologie', 'Cardiologie'), ('Pediatrie', 'Pediatrie'), ('Neurologie', 'Neurologie'), ('Oftalmologie', 'Oftalmologie'), ('Pshihiatrie', 'Pshihiatrie'), ('Radiologie', 'Radiologie')], max_length=264, null=True),
        ),
    ]
