# Generated by Django 3.1.5 on 2022-11-26 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20221126_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adauga_cabinet',
            old_name='departamente',
            new_name='specializare',
        ),
    ]
