# Generated by Django 3.1.5 on 2022-11-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20221126_0445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='nume',
            new_name='numele',
        ),
        migrations.RenameField(
            model_name='pacient',
            old_name='nume',
            new_name='numele',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='prenume',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='prenume',
        ),
    ]
