# Generated by Django 3.1.5 on 2022-11-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20221126_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='imagine',
            field=models.ImageField(default='profile_pic.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='imagine',
            field=models.ImageField(default='profile_pic.png', null=True, upload_to=''),
        ),
    ]
