# Generated by Django 3.1.5 on 2022-11-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20221126_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adauga_Pacienti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numele', models.CharField(max_length=264, null=True)),
                ('prenumele', models.CharField(max_length=264, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('nr_de_telefon', models.IntegerField(null=True)),
                ('data_nasterii', models.DateTimeField(null=True)),
                ('sex', models.CharField(choices=[('Femeie', 'Femeie'), ('Barbat', 'Barbat')], max_length=264, null=True)),
                ('judet', models.CharField(choices=[('Alba', 'Alba'), ('Arad', 'Arad'), ('Arges', 'Arges'), ('Bacau', 'Bacau'), ('Bihor', 'Bihor'), ('Bistrita-Nasaud', 'Bistrita-Nasaud'), ('Botosani', 'Botosani'), ('Braila', 'Braila'), ('Brasov', 'Brasov'), ('Buzau', 'Buzau'), ('Calarasi', 'Calarasi'), ('Caras-Severin', 'Caras-Severin'), ('Cluj', 'Cluj'), ('Constanta', 'Constanta'), ('Covasna', 'Covasna'), ('Dambovita', 'Dambovita'), ('Dolj', 'Dolj'), ('Galati', 'Galati'), ('Giurgiu', 'Giurgiu'), ('Gorj', 'Gorj'), ('Harghita', 'Harghita'), ('Hunedoara', 'Hunedoara'), ('Ialomita', 'Ialomita'), ('Iasi', 'Iasi'), ('Ilfov', 'Ilfov'), ('Maramures', 'Maramures'), ('Mehedinti', 'Mehedinti'), ('Mures', 'Mures'), ('Neamt', 'Neamt'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Salaj', 'Salaj'), ('Satu Mare', 'Satu Mare'), ('Sibiu', 'Sibiu'), ('Suceava', 'Suceava'), ('Teleorman', 'Teleorman'), ('Timis', 'Timis'), ('Tulcea', 'Tulcea'), ('Valcea', 'Valcea'), ('Vaslui', 'Vaslui'), ('Vrancea', 'Vrancea')], max_length=264, null=True)),
                ('localitate', models.CharField(max_length=264, null=True)),
                ('adresa', models.CharField(max_length=264, null=True)),
            ],
        ),
    ]
