# Generated by Django 3.1.5 on 2022-11-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_adauga_pacienti_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adauga_pacienti',
            name='data_nasterii',
            field=models.IntegerField(null=True),
        ),
    ]
