# Generated by Django 3.1.5 on 2022-11-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_servicii'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicii',
            name='moneda',
            field=models.CharField(choices=[('Euro', 'Euro'), ('Lei', 'Lei')], max_length=264, null=True),
        ),
    ]
