# Generated by Django 3.1.5 on 2022-11-27 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0014_recenzii'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=264, null=True)),
                ('ora', models.CharField(choices=[('6:30', '6:30'), ('7:30', '7:30'), ('8:30', '8:30'), ('9:30', '9:30'), ('10:30', '10:30'), ('11:30', '11:30'), ('12:30', '12:30'), ('13:30', '13:30'), ('14:30', '14:30'), ('15:30', '15:30'), ('16:30', '16:30'), ('17:30', '17:30'), ('18:30', '18:30'), ('19:30', '19:30'), ('20:30', '20:30'), ('21:30', '21:30'), ('22:30', '22:30'), ('23:30', '23:30'), ('24:00', '24:00'), ('Inchis', 'Inchis')], max_length=264, null=True)),
                ('afacere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.adauga_cabinet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
