# Generated by Django 3.1.5 on 2022-11-27 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0015_programare'),
    ]

    operations = [
        migrations.AddField(
            model_name='adauga_cabinet',
            name='favorit',
            field=models.ManyToManyField(blank=True, related_name='favorit', to=settings.AUTH_USER_MODEL),
        ),
    ]
